### ISSUE TITLE
Operator shutting down after one minute

### ISSUE THREAD

**Issue by heruan** [operator-framework/josdk-spring-boot-starter#202]
I'm trying to build a simple operator, right now it is just like this:

```java
@Informer
public class AppController implements Reconciler<App> {

    @Override
    public UpdateControl<App> reconcile(App app, Context<App> context) {
        System.out.println("RECONCILE RUNNING");
        return UpdateControl.noUpdate();
    }
}
```

When I start the app, after one minute it shuts down:

```
2025-01-29T18:07:41.176+01:00  INFO 92570 --- [           main] c.v.c.operator.OperatorApplication       : Started OperatorApplication in 1.203 seconds (process running for 1.381)
2025-01-29T18:07:41.177+01:00  INFO 92570 --- [           main] io.javaoperatorsdk.operator.Operator     : Operator SDK 5.0.0-beta1 (commit: dd40cbc) built on Fri Dec 06 12:07:51 CET 2024 starting...
2025-01-29T18:07:41.180+01:00  INFO 92570 --- [           main] io.javaoperatorsdk.operator.Operator     : Client version: 7.0.0
2025-01-29T18:07:41.181+01:00  INFO 92570 --- [: appcontroller] i.j.operator.processing.Controller       : Starting 'appcontroller' controller for reconciler: com.vaadin.controlcenter.operator.AppController, resource: com.vaadin.controlcenter.operator.App
2025-01-29T18:07:41.771+01:00  INFO 92570 --- [: appcontroller] i.j.operator.processing.Controller       : 'appcontroller' controller started
2025-01-29T18:08:41.777+01:00  INFO 92570 --- [ionShutdownHook] io.javaoperatorsdk.operator.Operator     : Operator SDK 5.0.0-beta1 is shutting down...
```

I still have no `App` custom resources created, I just noticed it shuts down for some reason. Is this expected?

**Comment by csviri** [comment]
Hi @heruan , no it is not, if you could share your code we can take a look.

Aren't you definening some health probes? My guess would be k8s is shutting it down.

**Comment by heruan** [comment]
No probes. I tested running from the IDE, still shuts down. Debugging looks like it's Spring shutting down and closing the operator, but why would Spring shut down once the operator is started?

Minimum reproducible code:

```kotlin
plugins {
    id("java")
    id("org.springframework.boot") version "3.4.2"
    id("io.spring.dependency-management") version "1.1.7"
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-logging")
    implementation("io.javaoperatorsdk:operator-framework-spring-boot-starter:6.0.0-beta2")
}
```

```java
package test;

import io.fabric8.kubernetes.api.model.KubernetesResource;
import io.fabric8.kubernetes.api.model.Namespaced;
import io.fabric8.kubernetes.client.CustomResource;
import io.fabric8.kubernetes.model.annotation.Group;
import io.fabric8.kubernetes.model.annotation.Version;
import test.App.AppSpec;
import test.App.AppStatus;

@Group("com.vaadin")
@Version("v1")
public class App extends CustomResource<AppSpec, AppStatus> implements
        Namespaced {

    record AppSpec() implements KubernetesResource {
    }

    record AppStatus() implements KubernetesResource {
    }
}
```
```java
package test;

import io.javaoperatorsdk.operator.api.config.informer.Informer;
import io.javaoperatorsdk.operator.api.reconciler.Context;
import io.javaoperatorsdk.operator.api.reconciler.Reconciler;
import io.javaoperatorsdk.operator.api.reconciler.UpdateControl;
import org.springframework.stereotype.Component;

@Informer
@Component
public class AppController implements Reconciler<App> {

    @Override
    public UpdateControl<App> reconcile(App app, Context<App> context) {
        System.out.println("RECONCILE RUNNING");
        return UpdateControl.noUpdate();
    }
}
```
```java
package test;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class OperatorApplication {

    public static void main(String... args) {
        SpringApplication.run(OperatorApplication.class, args);
    }
}
```

**Comment by csviri** [comment]
@heruan  how are you generating the CRD? or you apply that manually? can you please that too pls

**Comment by heruan** [comment]
The CRD is generated by Fabric8:

```yaml
# Generated by Fabric8 CRDGenerator, manual edits might get overwritten!
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "apps.com.vaadin"
spec:
  group: "com.vaadin"
  names:
    kind: "App"
    plural: "apps"
    singular: "app"
  scope: "Namespaced"
  versions:
  - name: "v1"
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: "object"
          status:
            type: "object"
        type: "object"
    served: true
    storage: true
    subresources:
      status: {}
```
